[font]
size = 7.5

[cursor]
style = "Block"

# [font.normal]
# family = "RobotoMono Nerd Font"


[window]
startup_mode = "Fullscreen"
dynamic_padding = true
opacity = 0.9

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"


[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

